name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  schedule:
    # Run every 30 minutes
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser beautifulsoup4 requests lxml

      - name: Generate news data
        run: |
          python generate_news.py

      - name: Commit updated news.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 
          'github-actions[bot]@users.noreply.github.com'
          git add news.json
          git commit -m "Update news data" || echo "No changes to commit"
          git push origin master

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: master
          force_orphan: true
